### ISSUE TITLE
Add sorting algorithm selection driver program to select different algorithms.

### ISSUE THREAD

**Issue by saurabh73** [saurabh73/sorting-algos#14]
Should have following features

 - [ ] Common Interface to accept input and display output
 - [ ] Ability to choose algorithm on fly
 - [ ] Display time taken and calculate order of complexity based on N.

**Comment by saurabh73** [comment]
Should have following features
- [ ] Common Interface to accept input and display output
- [ ] Ability to choose algorithm on fly
- [ ] Display time taken and calculate order of complexity based on N.

**Comment by MarikIshtar007** [comment]
Do you mean a common interface to select any algorithm and then use the selected sort?
Or a separate, yet similar interface within each of the algorithm files?

**Comment by saurabh73** [comment]
Common interact to select any sorting algorithm.

**Comment by MarikIshtar007** [comment]
Alright. I'll start on it.

**Comment by YaMo97** [comment]
Hi, @MarikIshtar007, are you working on this? Please let me know the status.

I have a vision in this regard and would like to implement it.

**Comment by MarikIshtar007** [comment]
Yes. I am working on it. I was thinking of using a header file to call the functions by using their prototypes in a common main driver file. Having some issues with it. 
What are your ideas?

**Comment by saurabh73** [comment]
#36
